

void resPlot(){
  //mean eta shift in MC pPb: -0.3336
  //mean eta shift in pPb Data: -0.1858
  TFile *f1 = new TFile("FullForest_v77_etaLT3_akPu3PF.root","OLD");
  TTree *dijetTree = (TTree*)f1->Get("dijetTree");
  TFile *f2 = new TFile("PythiaMIT_out_v77_etaLT3_akPu3PF.root","OLD");
  TTree *mcTree = (TTree*)f2->Get("dijetTree");
  TFile *f3 = new TFile("PythiaMIT_out_etaLT3_akPu3Calo.root","OLD");
  TTree *caloTree = (TTree*)f3->Get("dijetTree");
  TFile *f4 = new TFile("PythiaSignal_PP_MC_akPu3PF.root","OLD");
  TTree *ppmcTree = (TTree*)f4->Get("dijetTree");

  TH1D *phiRes = new TH1D("phiRes","",50,-0.1,0.1);
  phiRes->Sumw2();
  TH1D *etaRes = new TH1D("etaRes","",50,-0.1,0.1);
  etaRes->Sumw2();
  TH1D *tmp = new TH1D("tmp","",50,-0.1,0.1);
  tmp->Sumw2();
  
  TH1D *data_mR = new TH1D("data_mR","",60,0,0.3);
  data_mR->Sumw2();
  TH1D *mc_mR = new TH1D("mc_mR","",60,0,0.3);
  mc_mR->Sumw2();
  TH1D *tmp3 = new TH1D("tmp3","",60,0,0.3);
  tmp3->Sumw2();

  TH2D *phiResPt = new TH2D("phiResPt","",30,0,400,50,0,0.2);
  phiResPt->Sumw2();
  TH2D *etaResPt = new TH2D("etaResPt","",30,0,400,50,0,0.2);
  etaResPt->Sumw2();
  TH2D *ptResPt = new TH2D("ptResPt","",30,0,400,50,0,0.2);
  ptResPt->Sumw2();
  TH2D *tmp2 = new TH2D("tmp2","",30,0,400,50,0,0.2);
  tmp2->Sumw2();
  
  TH2D *phiResEta = new TH2D("phiResEta","",30,-3,3,50,0,0.2);
  phiResEta->Sumw2();
  TH2D *etaResEta = new TH2D("etaResEta","",30,-3,3,50,0,0.2);
  etaResEta->Sumw2();
  TH2D *ptResEta = new TH2D("ptResEta","",30,-3,3,50,0,0.2);
  ptResEta->Sumw2();
  TH2D *tmp4 = new TH2D("tmp4","",30,-3,3,50,0,0.2);
  tmp4->Sumw2();

  TH2D *phiResCent = new TH2D("phiResCent","",20,0,80,50,0,0.2);
  phiResCent->Sumw2();
  TH2D *etaResCent = new TH2D("etaResCent","",20,0,80,50,0,0.2);
  etaResCent->Sumw2();
  TH2D *ptResCent = new TH2D("ptResCent","",20,0,80,50,0,0.2);
  ptResCent->Sumw2();
  TH2D *tmp6 = new TH2D("tmp6","",20,0,80,50,0,0.2);
  tmp6->Sumw2();

  TH2D *ppphiResPt = new TH2D("ppphiResPt","",30,0,400,50,0,0.2);
  ppphiResPt->Sumw2();
  TH2D *ppetaResPt = new TH2D("ppetaResPt","",30,0,400,50,0,0.2);
  ppetaResPt->Sumw2();
  TH2D *ppptResPt = new TH2D("ppptResPt","",30,0,400,50,0,0.2);
  ppptResPt->Sumw2();
  TH2D *pptmp2 = new TH2D("pptmp2","",30,0,400,50,0,0.2);
  pptmp2->Sumw2();
  
  TH2D *ppphiResEta = new TH2D("ppphiResEta","",30,-3,3,50,0,0.2);
  ppphiResEta->Sumw2();
  TH2D *ppetaResEta = new TH2D("ppetaResEta","",30,-3,3,50,0,0.2);
  ppetaResEta->Sumw2();
  TH2D *ppptResEta = new TH2D("ppptResEta","",30,-3,3,50,0,0.2);
  ppptResEta->Sumw2();
  TH2D *pptmp4 = new TH2D("pptmp4","",30,-3,3,50,0,0.2);
  pptmp4->Sumw2();

  TH2D *ppphiResCent = new TH2D("ppphiResCent","",20,0,80,50,0,0.2);
  ppphiResCent->Sumw2();
  TH2D *ppetaResCent = new TH2D("ppetaResCent","",20,0,80,50,0,0.2);
  ppetaResCent->Sumw2();
  TH2D *ppptResCent = new TH2D("ppptResCent","",20,0,80,50,0,0.2);
  ppptResCent->Sumw2();
  TH2D *pptmp6 = new TH2D("pptmp6","",20,0,80,50,0,0.2);
  pptmp6->Sumw2();

  double xbins[7] = {0,5,10,15,20,30,70};
  TH2D *genAvgPhi = new TH2D("genAvgPhi","",10,-2,2,30,0,3.14);
  TH2D *recoAvgPhi = new TH2D("recoAvgPhi","",10,-2,2,30,0,3.14);
  TH2D *dataAvgPhi = new TH2D("dataAvgPhi","",10,-2,2,30,0,3.14);
  TH2D *caloAvgPhi = new TH2D("caloAvgPhi","",10,-2,2,30,0,3.14);
  TH2D *caloGenAvgPhi = new TH2D("caloGenAvgPhi","",10,-2,2,30,0,3.14);
  genAvgPhi->Sumw2();
  recoAvgPhi->Sumw2();
  dataAvgPhi->Sumw2();
  caloAvgPhi->Sumw2();
  caloGenAvgPhi->Sumw2();

  mcTree->Draw("acos(cos(genPhi1-genPhi2)):(genEta1+genEta2)/2>>genAvgPhi","(weight/MCpthatEntries)*(genPt1>120 && genPt2>30 && pthat>30 && rawPt1>15 && rawPt2>15)");
  mcTree->Draw("acos(cos(phi1-phi2)):(eta1+eta2)/2>>recoAvgPhi","(weight/MCpthatEntries)*(pt1>120 && pt2>30 && pthat>30 && rawPt1>15 && rawPt2>15)");
  dijetTree->Draw("acos(cos(phi1-phi2)):(eta1+eta2)/2>>dataAvgPhi","(pt1>120 && pt2>30 && rawPt1>15 && rawPt2>15)");
  caloTree->Draw("acos(cos(phi1-phi2)):(eta1+eta2)/2>>caloAvgPhi","(weight/MCpthatEntries)*(pt1>120 && pt2>30 && pthat>30 && rawPt1>15 && rawPt2>15)");
  caloTree->Draw("acos(cos(genPhi1-genPhi2)):(genEta1+genEta2)/2>>caloGenAvgPhi","(weight/MCpthatEntries)*(genPt1>120 && genPt2>30 && pthat>30 && rawPt1>15 && rawPt2>15)");

  TCanvas *c0_0 = new TCanvas("c0_0","",800,600);
  c0_0->cd();
  TH1D *p0_1 = genAvgPhi->ProfileX();
  cout << "gen MC <dphi>: " << p0_1->GetMean(2) << endl;
  TH1D *p0_2 = recoAvgPhi->ProfileX();
  cout << "reco MC <dphi>: " << p0_2->GetMean(2) << endl;
  TH1D *p0_3 = dataAvgPhi->ProfileX();
  cout << "reco data <dphi>: " << p0_3->GetMean(2) << endl;
  TH1D *p0_4 = caloAvgPhi->ProfileX();
  cout << "calo MC <dphi>: "<< p0_4->GetMean(2) << endl;
  TH1D *p0_5 = caloGenAvgPhi->ProfileX();
  cout << "calo Gen MC <dphi>: " << p0_5->GetMean(2) << endl;
  p0_2->SetLineColor(2);
  p0_2->SetMarkerColor(2);
  p0_4->SetLineColor(kOrange-3);
  p0_4->SetMarkerColor(kOrange-3);
  p0_1->SetLineColor(kCyan+1);
  p0_1->SetMarkerColor(kCyan+1);
  p0_5->SetMarkerColor(kBlue-9);
  p0_5->SetLineColor(kBlue-9);
  p0_1->SetMaximum(3.05);
  p0_1->SetMinimum(2.5);
  p0_1->SetXTitle("(#eta_{1}+#eta_{2})/2");
  p0_1->SetYTitle("<#Delta#phi>");
  p0_1->Draw();
  p0_3->Draw("same");
  p0_2->Draw("same");
  p0_4->Draw("same");
  p0_5->Draw("same");
  TLegend *l1 = new TLegend(0.2,0.77,0.80,0.91);
  l1->AddEntry(p0_1,"Pythia+Hijing MC, PF Gen Level");
  l1->AddEntry(p0_2,"Pythia+Hijing MC, PF Reco Level");
  l1->AddEntry(p0_5,"Pythia+Hijing MC, Calo Gen Level");
  l1->AddEntry(p0_4,"Pythia+Hijing MC, Calo Reco Level");
  l1->AddEntry(p0_3,"pPb data, #sqrt{s}=5 TeV");
  l1->Draw();

  TCanvas *c1 = new TCanvas("c1","",1200,700);
  c1->cd();

  mcTree->Draw("refPhi1-phi1>>phiRes","(weight/MCpthatEntries)*1");
  mcTree->Draw("refPhi2-phi2>>tmp","(weight/MCpthatEntries)*1");
  phiRes->Add(tmp);
  mcTree->Draw("refEta1-eta1>>etaRes","(weight/MCpthatEntries)*1");
  mcTree->Draw("refEta2-eta2>>tmp","(weight/MCpthatEntries)*1");
  etaRes->Add(tmp);

  mcTree->Draw("abs(refPhi1-phi1):pt1>>phiResPt","(weight/MCpthatEntries)*1");
  mcTree->Draw("abs(refPhi2-phi2):pt2>>tmp2","(weight/MCpthatEntries)*1");
  phiResPt->Add(tmp2);
  mcTree->Draw("abs(refEta1-eta1):pt1>>etaResPt","(weight/MCpthatEntries)*1");
  mcTree->Draw("abs(refEta2-eta2):pt2>>tmp2","(weight/MCpthatEntries)*1");
  etaResPt->Add(tmp2);
  mcTree->Draw("abs(refPt1-pt1):pt1>>ptResPt","(weight/MCpthatEntries)*1");
  mcTree->Draw("abs(refPt2-pt2):pt2>>tmp2","(weight/MCpthatEntries)*1");
  ptResPt->Add(tmp2);

  mcTree->Draw("abs(refPhi1-phi1):(eta1+eta2)/2>>phiResEta","(weight/MCpthatEntries)*1");
  mcTree->Draw("abs(refPhi2-phi2):(eta1+eta2)/2>>tmp4","(weight/MCpthatEntries)*1");
  phiResEta->Add(tmp4);
  mcTree->Draw("abs(refEta1-eta1):(eta1+eta2)/2>>etaResEta","(weight/MCpthatEntries)*1");
  mcTree->Draw("abs(refEta2-eta2):(eta1+eta2)/2>>tmp4","(weight/MCpthatEntries)*1");
  etaResEta->Add(tmp4);
  mcTree->Draw("abs(refPt1-pt1):(eta1+eta2)/2>>ptResEta","(weight/MCpthatEntries)*1");
  mcTree->Draw("abs(refPt2-pt2):(eta1+eta2)/2>>tmp4","(weight/MCpthatEntries)*1");
  ptResEta->Add(tmp4);

  mcTree->Draw("abs(refPhi1-phi1):(hiHFplusEta4+hiHFminusEta4)>>phiResCent","(weight/MCpthatEntries)*1");
  mcTree->Draw("abs(refPhi2-phi2):(hiHFplusEta4+hiHFminusEta4)>>tmp6","(weight/MCpthatEntries)*1");
  phiResCent->Add(tmp6);
  mcTree->Draw("abs(refEta1-eta1):(hiHFplusEta4+hiHFminusEta4)>>etaResCent","(weight/MCpthatEntries)*1");
  mcTree->Draw("abs(refEta2-eta2):(hiHFplusEta4+hiHFminusEta4)>>tmp6","(weight/MCpthatEntries)*1");
  etaResCent->Add(tmp6);
  mcTree->Draw("abs(refPt1-pt1):(hiHFplusEta4+hiHFminusEta4)>>ptResCent","(weight/MCpthatEntries)*1");
  mcTree->Draw("abs(refPt2-pt2):(hiHFplusEta4+hiHFminusEta4)>>tmp6","(weight/MCpthatEntries)*1");
  ptResCent->Add(tmp6);

  ppmcTree->Draw("abs(refPhi1-phi1):pt1>>ppphiResPt","(weight/MCpthatEntries)*(pthat>30)");
  ppmcTree->Draw("abs(refPhi2-phi2):pt2>>pptmp2","(weight/MCpthatEntries)*(pthat>30)");
  ppphiResPt->Add(pptmp2);
  ppmcTree->Draw("abs(refEta1-eta1):pt1>>ppetaResPt","(weight/MCpthatEntries)*(pthat>30)");
  ppmcTree->Draw("abs(refEta2-eta2):pt2>>pptmp2","(weight/MCpthatEntries)*(pthat>30)");
  ppetaResPt->Add(pptmp2);
  ppmcTree->Draw("abs(refPt1-pt1):pt1>>ppptResPt","(weight/MCpthatEntries)*(pthat>30)");
  ppmcTree->Draw("abs(refPt2-pt2):pt2>>pptmp2","(weight/MCpthatEntries)*(pthat>30)");
  ppptResPt->Add(pptmp2);

  ppmcTree->Draw("abs(refPhi1-phi1):(eta1+eta2)/2>>ppphiResEta","(weight/MCpthatEntries)*1");
  ppmcTree->Draw("abs(refPhi2-phi2):(eta1+eta2)/2>>pptmp4","(weight/MCpthatEntries)*1");
  ppphiResEta->Add(pptmp4);
  ppmcTree->Draw("abs(refEta1-eta1):(eta1+eta2)/2>>ppetaResEta","(weight/MCpthatEntries)*1");
  ppmcTree->Draw("abs(refEta2-eta2):(eta1+eta2)/2>>pptmp4","(weight/MCpthatEntries)*1");
  ppetaResEta->Add(pptmp4);
  ppmcTree->Draw("abs(refPt1-pt1):(eta1+eta2)/2>>ppptResEta","(weight/MCpthatEntries)*1");
  ppmcTree->Draw("abs(refPt2-pt2):(eta1+eta2)/2>>pptmp4","(weight/MCpthatEntries)*1");
  ppptResEta->Add(pptmp4);

  ppmcTree->Draw("abs(refPhi1-phi1):(hiHFplusEta4+hiHFminusEta4)>>ppphiResCent","(weight/MCpthatEntries)*1");
  ppmcTree->Draw("abs(refPhi2-phi2):(hiHFplusEta4+hiHFminusEta4)>>pptmp6","(weight/MCpthatEntries)*1");
  ppphiResCent->Add(pptmp6);
  ppmcTree->Draw("abs(refEta1-eta1):(hiHFplusEta4+hiHFminusEta4)>>ppetaResCent","(weight/MCpthatEntries)*1");
  ppmcTree->Draw("abs(refEta2-eta2):(hiHFplusEta4+hiHFminusEta4)>>pptmp6","(weight/MCpthatEntries)*1");
  ppetaResCent->Add(pptmp6);
  ppmcTree->Draw("abs(refPt1-pt1):(hiHFplusEta4+hiHFminusEta4)>>ppptResCent","(weight/MCpthatEntries)*1");
  ppmcTree->Draw("abs(refPt2-pt2):(hiHFplusEta4+hiHFminusEta4)>>pptmp6","(weight/MCpthatEntries)*1");
  ppptResCent->Add(pptmp6);

  mcTree->Draw("calodr1>>mc_mR","(weight/MCpthatEntries)*1");
  mcTree->Draw("calodr2>>tmp3","(weight/MCpthatEntries)*1");
  mc_mR->Add(tmp3);
  dijetTree->Draw("calodr1>>data_mR","(weight/MCpthatEntries)*1");
  dijetTree->Draw("calodr2>>tmp3","(weight/MCpthatEntries)*1");
  data_mR->Add(tmp3);

  TCanvas *c0 = new TCanvas("c0","",800,600);
  c0->cd();
  data_mR->SetXTitle("#Delta R, Calo->PF Jet");
  data_mR->Scale(1./data_mR->Integral());
  data_mR->Draw();
  mc_mR->SetMarkerColor(2);
  mc_mR->SetLineColor(2);
  mc_mR->Scale(1./mc_mR->Integral());
  mc_mR->Draw("same");

  //TCanvas *c1 = new TCanvas("c1","",1200,700);
  c1->Clear();
  c1->Divide(2,1);
  c1->cd(1);
  phiRes->SetXTitle("#phi_{ref}- #phi_{reco}");
  phiRes->Draw();
  phiRes->Fit("gaus","","",-0.05,0.05);
  c1->cd(2);
  etaRes->SetXTitle("#eta_{ref}- #eta_{reco}");
  etaRes->Draw();
  etaRes->Fit("gaus","","",-0.05,0.05);

  TCanvas *c2 = new TCanvas("c2","",1200,700);
  c2->Divide(3,1);
  c2->cd(1);
  TH1D *p1 = phiResPt->ProfileX();
  TH1D *ppp1 = ppphiResPt->ProfileX();
  p1->SetXTitle("Single Jet p_{T} (GeV/c)");
  p1->SetTitleOffset(1.5,"y");
  p1->SetYTitle("|#phi_{ref}- #phi_{reco}|");
  p1->SetMinimum(0.01);
  p1->Draw();
  ppp1->SetMarkerColor(2);
  ppp1->SetLineColor(2);
  ppp1->Draw("same");
  TLatex *t1 = new TLatex(250,0.03,"CMS Preliminary");
  t1->Draw();
  TLatex *t2 = new TLatex(250,0.026,"p_{T,1}>120 GeV/c, p_{T,2}>30 GeV/c");
  t2->Draw();
  TLatex *t3 = new TLatex(250,0.022,"|#eta|<3");
  t3->Draw();
  TLatex *t4 = new TLatex(250,0.019,"Inclusive E_{T}^{HF[|#eta|>4]}");
  t4->Draw();
  c2->cd(2);
  TH1D *p2 = etaResPt->ProfileX();
  TH1D *ppp2 = ppetaResPt->ProfileX();
  p2->SetXTitle("Reconstructed p_{T} (GeV/c)");
  p2->SetTitleOffset(1.5,"y");
  p2->SetYTitle("|#eta_{ref}- #eta_{reco}|");
  p2->SetMinimum(0.01);
  p2->Draw();
  ppp2->SetMarkerColor(2);
  ppp2->SetLineColor(2);
  ppp2->Draw("same");
  TLegend *leg1 = new TLegend(0.5,0.78,0.8,0.91);
  leg1->AddEntry(p2,"PYTHIA+HIJING pPb, #sqrt{s_{NN}}=5.02 TeV");
  leg1->AddEntry(ppp2,"PYTHIA+HIJING pp, #sqrt{s_{NN}}=5.02 TeV");
  leg1->SetFillColor(0);
  leg1->Draw();
  c2->cd(3);
  TH1D *p2_1 = ptResPt->ProfileX();
  TH1D *ppp2_1 = ppptResPt->ProfileX();
  p2_1->SetXTitle("Reconstructed p_{T} (GeV/c)");
  p2_1->SetTitleOffset(1.5,"y");
  p2_1->SetYTitle("|p_{T,ref}- p_{T,reco}|");
  p2_1->Draw();
  ppp2_1->SetMarkerColor(2);
  ppp2_1->SetLineColor(2);
  ppp2_1->Draw("same");
  

  TCanvas *c3 = new TCanvas("c3","",1200,700);
  c3->Divide(3,1);
  c3->cd(1);
  TH1D *p3 = phiResEta->ProfileX();
  TH1D *ppp3 = ppphiResEta->ProfileX();
  p3->SetXTitle("(#eta_{1}+#eta_{2})/2");
  p3->SetTitleOffset(1.5,"y");
  p3->SetYTitle("|#phi_{gen}- #phi_{reco}|");
  p3->Draw();
  ppp3->SetMarkerColor(2);
  ppp3->SetLineColor(2);
  ppp3->Draw("same");
  TLatex *t11 = new TLatex(0,0.028,"CMS Preliminary");
  t11->Draw();
  TLatex *t21 = new TLatex(0,0.026,"p_{T,1}>120 GeV, p_{T,2}>30 GeV");
  t21->Draw();
  TLatex *t31 = new TLatex(0,0.024,"|#eta|<3");
  t31->Draw();
  TLatex *t41 = new TLatex(0,0.022,"Inclusive E_{T}^{HF[|#eta|>4]}");
  t41->Draw();
  c3->cd(2);
  TH1D *p4 = etaResEta->ProfileX();
  TH1D *ppp4 = ppetaResEta->ProfileX();
  p4->SetXTitle("(#eta_{1}+#eta_{2})/2");
  p4->SetTitleOffset(1.5,"y");
  p4->SetYTitle("|#eta_{gen}- #eta_{reco}|");
  p4->Draw();
  ppp4->SetMarkerColor(2);
  ppp4->SetLineColor(2);
  ppp4->Draw("same");
  TLegend *leg2 = new TLegend(0.5,0.78,0.8,0.91);
  leg2->AddEntry(p4,"PYTHIA+HIJING pPb, #sqrt{s_{NN}}=5.02 TeV");
  leg2->AddEntry(ppp4,"PYTHIA+HIJING pp, #sqrt{s_{NN}}=5.02 TeV");
  leg2->SetFillColor(0);
  leg2->Draw();
  c3->cd(3);
  TH1D *p4_1 = ptResEta->ProfileX();
  TH1D *ppp4_1 = ppptResEta->ProfileX();
  p4_1->SetXTitle("(#eta_{1}+#eta_{2})/2");
  p4_1->SetTitleOffset(1.5,"y");
  p4_1->SetYTitle("|p_{T,gen}- p_{T,reco}|");
  p4_1->Draw();
  ppp4_1->SetMarkerColor(2);
  ppp4_1->SetLineColor(2);
  ppp4_1->Draw("same");

  TCanvas *c4 = new TCanvas("c4","",1200,700);
  c4->Divide(3,1);
  c4->cd(1);
  TH1D *p5 = phiResCent->ProfileX();
  TH1D *ppp5 = ppphiResCent->ProfileX();
  p5->SetXTitle("E_{T}^{HF[|#eta|>4]}");
  p5->SetTitleOffset(1.5,"y");
  p5->SetYTitle("|#phi_{gen}- #phi_{reco}|");
  p5->SetMinimum(0.01);
  p5->SetMaximum(0.035);
  p5->Draw();
  ppp5->SetMarkerColor(2);
  ppp5->SetLineColor(2);
  ppp5->Draw("same");
  TLatex *t12 = new TLatex(0,0.028,"CMS Preliminary");
  t12->Draw();
  TLatex *t22 = new TLatex(0,0.026,"p_{T,1}>120 GeV, p_{T,2}>30 GeV");
  t22->Draw();
  TLatex *t32 = new TLatex(0,0.024,"|#eta|<3");
  t32->Draw();
  TLatex *t42 = new TLatex(0,0.022,"Inclusive E_{T}^{HF[|#eta|>4]}");
  t42->Draw();
  c4->cd(2);
  TH1D *p6 = etaResCent->ProfileX();
  TH1D *ppp6 = ppetaResCent->ProfileX();
  p6->SetXTitle("E_{T}^{HF[|#eta|>4]}");
  p6->SetTitleOffset(1.5,"y");
  p6->SetYTitle("|#eta_{ref}- #eta_{reco}|");
  p6->SetMinimum(0.01);
  p6->SetMaximum(0.035);
  p6->Draw();
  ppp6->SetMarkerColor(2);
  ppp6->SetLineColor(2);
  ppp6->Draw("same");
  TLegend *leg3 = new TLegend(0.5,0.78,0.8,0.91);
  leg3->AddEntry(p6,"PYTHIA+HIJING pPb, #sqrt{s_{NN}}=5.02 TeV");
  leg3->AddEntry(ppp6,"PYTHIA+HIJING pp, #sqrt{s_{NN}}=5.02 TeV");
  leg3->SetFillColor(0);
  leg3->Draw();
  c4->cd(3);
  TH1D *p6_1 = ptResCent->ProfileX();
  TH1D *ppp6_1 = ppptResCent->ProfileX();
  p6_1->SetXTitle("E_{T}^{HF[|#eta|>4]}");
  p6_1->SetTitleOffset(1.5,"y");
  p6_1->SetYTitle("|p_{T,ref}- p_{T,reco}|");
  p6_1->Draw();
  ppp6_1->SetMarkerColor(2);
  ppp6_1->SetLineColor(2);
  ppp6_1->Draw("same");

}
